TrainingDiary/Controllers/CoachDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrainingDiary.Enums;
using TrainingDiary.Models;
using TrainingDiary.Services;
using TrainingDiary.ViewModels;

namespace TrainingDiary.Controllers
{
    // Coach only
    [Authorize(Roles = Role.Coach)]
    public class CoachDashboardController : Controller
    {
        private readonly IDbContextService _dbContextService;
        private readonly IUserService _userService;

        public CoachDashboardController(IDbContextService dbContextService, IUserService userService)
        {
            _dbContextService = dbContextService;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            Coach coach = await _userService.GetUser(User) as Coach;

            if (coach == null)
            {
                return NotFound();
            }

            coach.PlayersList = await _dbContextService.GetPlayersForCoach(coach.Id);

            if (coach.PlayersList.Any())
            {
                IEnumerable<PlayerViewModel> playersViewModels = coach.PlayersList.Select(x => new PlayerViewModel(x)).ToList();
                return View(playersViewModels);
            }
            else
            {
                return RedirectToAction(nameof(NoPlayers));
            }
        }

        //TODO: Details, Delete

        public IActionResult NoPlayers()
        {
            return View();
        }

        public async Task<IActionResult> PlayerDetails(string id)
        {
            if(id == null)
            {
                return NotFound("Unable to load user.");
            }
            var user = await _userService.GetUserByEmail(id);
            if (user == null)
            {
                return NotFound("Unable to load user.");
            }

            if (user is Player player)
            {
                PlayerViewModel playerVM = new PlayerViewModel(player);
                return View(playerVM);
            }
            else
            {
                return NotFound("Unable to load user.");
            }
        }
        public async Task<IActionResult> DeleteConnection(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User user = await _userService.GetUserByEmail(id);
            if (user == null)
            {
                return NotFound();
            }
            if (user is Player player)
            {
                PlayerViewModel playerVM = new PlayerViewModel(player);
                return View(playerVM);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost, ActionName("DeleteConnection")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            User user = await _userService.GetUserByEmail(id);
            await _dbContextService.DeleteRelationBetweenCoachAndPlayer(user);
            return RedirectToAction(nameof(Index));
        }
    }
}

TrainingDiary/Views/CoachDashboard/DeleteConnection.cshtml
@model TrainingDiary.ViewModels.PlayerViewModel

<h4>
    Are you sure you want to remove this player?
</h4>
<hr />
<p>
    Removing a player will remove the connection with him.
    <br />
    That means you won't be his trainer.
</p>
<div>
    <h4>Player details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LicenceNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LicenceNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ShoeSize)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ShoeSize)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ExaminationDeadline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ExaminationDeadline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Injured)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Injured)
        </dd>
    </dl>

    <form asp-action="DeleteConnection">
        <input type="hidden" asp-for="Email" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TrainingDiary/Views/CoachDashboard/Index.cshtml
@{
    ViewData["Title"] = "My players";
}
@model IEnumerable<PlayerViewModel>
@using TrainingDiary.ViewModels

<h2>@ViewData["Title"]</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (PlayerViewModel player in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(x => player.FirstName)
            </td>
            <td>
                @Html.DisplayFor(x => player.LastName)
            </td>
            <td>
                @Html.DisplayFor(x => player.Email)
            </td>
            <td>
                <a asp-controller="CoachDashboard" asp-action="PlayerDetails" asp-route-id="@player.Email">Details</a> |
                <a asp-action="DeleteConnection" asp-route-id="@player.Email">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

TrainingDiary/Views/CoachDashboard/NoPlayers.cshtml
<h4>
    You don't have any players.
</h4>

TrainingDiary/Views/CoachDashboard/PlayerDetails.cshtml
@model TrainingDiary.ViewModels.PlayerViewModel

<div>
    <h4>Player details</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LicenceNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LicenceNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoeSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoeSize)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExaminationDeadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExaminationDeadline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Injured)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Injured)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>