TrainingDiary/Models/Start.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;
using TrainingDiary.Enums;

namespace TrainingDiary.Models
{
    public class Start : BaseEvent
    {
        [DisplayName("Place")]
        public string Place {get; set;}
        [DisplayName("Result")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm\\:ss\\,FFF}")]
        public TimeSpan Result {get; set;}
        [DisplayName("Distance")]
        public float Distance {get; set;}
        [DisplayName("Location")]
        public string Location {get; set;}
        [DisplayName("Coach comment")]
        public string CoachComment {get;set;}
        [DisplayName("Player comment")]
        public string PlayerComment {get;set;}

        public Start()
        {
            Type = EventType.Start;
            CalendarColor = ColorTranslator.ToHtml(Color.Red);
        }
    }
}

TrainingDiary/Controllers/StartController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrainingDiary.Enums;
using TrainingDiary.Models;
using TrainingDiary.Services;

namespace TrainingDiary.Controllers
{
    [Authorize]
    public class StartController : Controller
    {
        private readonly IUserService _userService;
        private readonly IDbContextService _dbContextService;

        public StartController(IUserService userService, IDbContextService dbContextService)
        {
            _userService = userService;
            _dbContextService = dbContextService;
        }

        private bool IsStartRelatedToCurrentUser(Start start)
        {
            string userId = _userService.GetUserId(User);
            if (User.IsInRole(Role.Player))
            {
                if (start.Player == null || start.Player.Id != userId)
                {
                    return false;
                }
            }
            else if (User.IsInRole(Role.Coach))
            {
                if (start.Coach == null || start.Coach.Id != userId)
                {
                    return false;
                }
            }

            return true;
        }

        // GET: Start/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var start = await _dbContextService.GetStartByIdAsync((int)id);
            if (start == null || !IsStartRelatedToCurrentUser(start))
            {
                return NotFound();
            }

            return View(start);
        }

        // GET: Start/Create
        [Authorize(Roles = Role.Coach)]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Start/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Role.Coach)]
        public async Task<IActionResult> Create(Start start)
        {
            if (ModelState.IsValid)
            {
                start.Player = await _userService.GetUserByEmail(start.PlayerEmail) as Player;
                start.Coach = await _userService.GetUser(User) as Coach;

                await _userService.SetUserInStartModel(start, User);
                await _dbContextService.AddObjectToDb(start);

                return RedirectToAction("Index", "Events");
            }
            return View(start);
        }

        // GET: Start/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var start = await _dbContextService.GetStartByIdAsync((int)id);
            if (start == null || !IsStartRelatedToCurrentUser(start))
            {
                return NotFound();
            }
            return View(start);
        }

        // POST: Start/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Place,Result,Distance,Location,CoachComment,PlayerComment,Id,EventName,StartDate,EndDate,Type")] Start start)
        {
            if (id != start.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _dbContextService.UpdateObjectInDb(start);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dbContextService.StartExists(start.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Events");
            }
            return View(start);
        }

        // GET: Start/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var start = await _dbContextService.GetStartByIdAsync((int)id);
            if (start == null || !IsStartRelatedToCurrentUser(start))
            {
                return NotFound();
            }

            return View(start);
        }

        // POST: Start/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var start = await _dbContextService.GetStartByIdAsync(id);
            await _dbContextService.RemoveStartFromDb(start);

            return RedirectToAction("Index", "Events");
        }
    }
}

TrainingDiary/Views/Start/Create.cshtml
@model TrainingDiary.Models.Start
@using TrainingDiary.Enums
<h4>Start</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <partial name="_BaseEventCreatePartial" />
                <div class="form-group">
                    <label asp-for="Place" class="control-label"></label>
                    <input asp-for="Place" class="form-control" />
                    <span asp-validation-for="Place" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Result" class="control-label"></label>
                    <input asp-for="Result" type="time" step="0.1" class="form-control" />
                    <span asp-validation-for="Result" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Distance" class="control-label"></label>
                    <input asp-for="Distance" class="form-control" />
                    <span asp-validation-for="Distance" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Location" class="control-label"></label>
                    <input asp-for="Location" class="form-control" />
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
                @{
                    if (User.IsInRole(Role.Coach))
                    {
                        <div class="form-group">
                            <label asp-for="CoachComment" class="control-label"></label>
                            <input asp-for="CoachComment" class="form-control" />
                            <span asp-validation-for="CoachComment" class="text-danger"></span>
                        </div>
                    }
                    else if (User.IsInRole(Role.Player))
                    {
                        <div class="form-group">
                            <label asp-for="PlayerComment" class="control-label"></label>
                            <input asp-for="PlayerComment" class="form-control" />
                            <span asp-validation-for="PlayerComment" class="text-danger"></span>
                        </div>
                    }
                }
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-secondary" />
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingDiary/Views/Start/Delete.cshtml
@model TrainingDiary.Models.Start

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Start</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Place)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Distance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Distance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoachComment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoachComment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerComment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerComment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div

TrainingDiary/Views/Start/Details.cshtml
@{
    ViewData["Title"] = "Start details";
}
@model Start
<partial name="_BaseEventDetailsPartial" />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Place)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Distance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Distance)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CoachComment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CoachComment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerComment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlayerComment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>

TrainingDiary/Views/Start/Edit.cshtml
@model TrainingDiary.Models.Start
@using TrainingDiary.Enums


<h4>Start</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (User.IsInRole(Role.Coach))
            {
                <partial name="_BaseEventEditPartial" />
            }
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Result" class="control-label"></label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Distance" class="control-label"></label>
                <input asp-for="Distance" class="form-control" />
                <span asp-validation-for="Distance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            @{
                if (User.IsInRole(Role.Coach))
                {
                    <div class="form-group">
                        <label asp-for="CoachComment" class="control-label"></label>
                        <input asp-for="CoachComment" class="form-control" />
                        <span asp-validation-for="CoachComment" class="text-danger"></span>
                    </div>
                }
                else if (User.IsInRole(Role.Player))
                {
                    <div class="form-group">
                        <label asp-for="PlayerComment" class="control-label"></label>
                        <input asp-for="PlayerComment" class="form-control" />
                        <span asp-validation-for="PlayerComment" class="text-danger"></span>
                    </div>
                }
            }
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingDiary/Views/Start/Index.cshtml
@model IEnumerable<TrainingDiary.Models.Start>
@using TrainingDiary.Enums;

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Result)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Distance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CoachComment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerComment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>

            <th style="min-width: 150px">
                @if (User.IsInRole(Role.Coach))
                {
                    <a class="btn btn-secondary" asp-controller="Start" asp-action="Create">Create New</a>
                }
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Place)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Result)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Distance)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CoachComment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerComment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>

                <td>
                    <a asp-controller="Start" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Start" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="Start" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>