TrainingDiary/Models/FullWorkout.cs
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Drawing;
using TrainingDiary.Enums;

namespace TrainingDiary.Models
{
    public class FullWorkout : BaseEvent
    {
        private readonly ILazyLoader lazyLoader;
        private Workout plan;
        private Workout realization;

        public FullWorkout()
        {
            Type = EventType.Fullworkout;
            CalendarColor = ColorTranslator.ToHtml(Color.Blue);
        }

        FullWorkout(ILazyLoader lazyLoader) : this()
        {
            this.lazyLoader = lazyLoader;
        }

        public Workout Plan
        {
            get => lazyLoader.Load(this, ref plan);
            set => plan = value;
        }
        public Workout Realization
        {
            get => lazyLoader.Load(this, ref realization);
            set => realization = value;
        }

    }
}

TrainingDiary/Controllers/FullWorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrainingDiary.Enums;
using TrainingDiary.Models;
using TrainingDiary.Services;

namespace TrainingDiary.Controllers
{
    [Authorize]
    public class FullWorkoutController : Controller
    {
        private readonly IDbContextService _dbContextService;
        private readonly IUserService _userService;

        public FullWorkoutController(IDbContextService dbContextService,IUserService userService)
        {
            _dbContextService = dbContextService;
            _userService = userService;
        }

        private bool IsFullWorkoutRelatedToCurrentUser(FullWorkout fullWorkout)
        {
            string userId = _userService.GetUserId(User);
            if (User.IsInRole(Role.Player))
            {
                if (fullWorkout.Player == null || fullWorkout.Player.Id != userId)
                {
                    return false;
                }
            }
            else if (User.IsInRole(Role.Coach))
            {
                if (fullWorkout.Coach == null || fullWorkout.Coach.Id != userId)
                {
                    return false;
                }
            }

            return true;
        }

        // GET: FullWorkouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fullWorkout = await _dbContextService.GetFullWorkoutByIdAsync((int)id);
            if (fullWorkout == null || !IsFullWorkoutRelatedToCurrentUser(fullWorkout))
            {
                return NotFound();
            }

            return View(fullWorkout);
        }

        // GET: FullWorkouts/Create
        [Authorize(Roles = Role.Coach)]
        public IActionResult Create()
        {
            return View();
        }

        // POST: FullWorkouts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Role.Coach)]
        public async Task<IActionResult> Create(FullWorkout fullWorkout)
        {
            if (ModelState.IsValid)
            {
                fullWorkout.Player = await _userService.GetUserByEmail(fullWorkout.PlayerEmail) as Player;
                fullWorkout.Coach = await _userService.GetUser(User) as Coach;

                await _dbContextService.AddObjectToDb(fullWorkout);
                await _dbContextService.SetConnectionToCamp(fullWorkout);

                return RedirectToAction("Index", "Events");
            }
            return View(fullWorkout);
        }

        // GET: FullWorkouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fullWorkout = await _dbContextService.GetFullWorkoutByIdAsync((int)id);
            if (fullWorkout == null || !IsFullWorkoutRelatedToCurrentUser(fullWorkout))
            {
                return NotFound();
            }
            return View(fullWorkout);
        }

        // POST: FullWorkouts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventName,StartDate,EndDate, Plan, Realization")] FullWorkout fullWorkout)
        {
            if (id != fullWorkout.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _dbContextService.UpdateObjectInDb(fullWorkout);
                    //_dbContextService.SetConnectionToCamp(fullWorkout);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dbContextService.FullWorkoutExists(fullWorkout.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Events");
            }
            return View(fullWorkout);
        }

        // GET: FullWorkouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fullWorkout = await _dbContextService.GetFullWorkoutByIdAsync((int)id);
            if (fullWorkout == null || !IsFullWorkoutRelatedToCurrentUser(fullWorkout))
            {
                return NotFound();
            }

            return View(fullWorkout);
        }

        // POST: FullWorkouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fullWorkout = await _dbContextService.GetFullWorkoutByIdAsync(id);
            await _dbContextService.RemoveFullWorkoutFromDb(fullWorkout);

            return RedirectToAction("Index", "Events");
        }
    }
}

TrainingDiary/Views/Fullworkout/Create.cshtml
@model TrainingDiary.Models.FullWorkout

<h4>FullWorkout</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <partial name="_BaseEventCreatePartial" />

                <h4>Training plan </h4>
                <div class="form-group">
                    <label asp-for="@Model.Plan.Content" class="control-label"></label>
                    <input asp-for="@Model.Plan.Content" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.OWB1" class="control-label"></label>
                    <input asp-for="@Model.Plan.OWB1" class="form-control" />
                    <span asp-validation-for="@Model.Plan.OWB1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.OWB2" class="control-label"></label>
                    <input asp-for="@Model.Plan.OWB2" class="form-control" />
                    <span asp-validation-for="@Model.Plan.OWB2" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.WB3" class="control-label"></label>
                    <input asp-for="@Model.Plan.WB3" class="form-control" />
                    <span asp-validation-for="@Model.Plan.WB3" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.ZB" class="control-label"></label>
                    <input asp-for="@Model.Plan.ZB" class="form-control" />
                    <span asp-validation-for="@Model.Plan.ZB" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.KR" class="control-label"></label>
                    <input asp-for="@Model.Plan.KR" class="form-control" />
                    <span asp-validation-for="@Model.Plan.KR" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.GL" class="control-label"></label>
                    <input asp-for="@Model.Plan.GL" class="form-control" />
                    <span asp-validation-for="@Model.Plan.GL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.DL" class="control-label"></label>
                    <input asp-for="@Model.Plan.DL" class="form-control" />
                    <span asp-validation-for="@Model.Plan.DL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.Rhythm" class="control-label"></label>
                    <input asp-for="@Model.Plan.Rhythm" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Rhythm" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.RelativeSpeed" class="control-label"></label>
                    <input asp-for="@Model.Plan.RelativeSpeed" class="form-control" />
                    <span asp-validation-for="@Model.Plan.RelativeSpeed" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.MaxSpeed" class="control-label"></label>
                    <input asp-for="@Model.Plan.MaxSpeed" class="form-control" />
                    <span asp-validation-for="@Model.Plan.MaxSpeed" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.Skip" class="control-label"></label>
                    <input asp-for="@Model.Plan.Skip" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Skip" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.MultipleJump" class="control-label"></label>
                    <input asp-for="@Model.Plan.MultipleJump" class="form-control" />
                    <span asp-validation-for="@Model.Plan.MultipleJump" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.MS" class="control-label"></label>
                    <input asp-for="@Model.Plan.MS" class="form-control" />
                    <span asp-validation-for="@Model.Plan.MS" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.BPG" class="control-label"></label>
                    <input asp-for="@Model.Plan.BPG" class="form-control" />
                    <span asp-validation-for="@Model.Plan.BPG" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.KMStart" class="control-label"></label>
                    <input asp-for="@Model.Plan.KMStart" class="form-control" />
                    <span asp-validation-for="@Model.Plan.KMStart" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.Scamper" class="control-label"></label>
                    <input asp-for="@Model.Plan.Scamper" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Scamper" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Plan.Comment" class="control-label"></label>
                    <input asp-for="@Model.Plan.Comment" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Comment" class="text-danger"></span>
                </div>
                <input type="submit" value="Create" class="btn btn-secondary" />
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingDiary/Views/Fullworkout/Delete.cshtml
@model TrainingDiary.Models.FullWorkout

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FullWorkout</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
    </form>
</div>

TrainingDiary/Views/Fullworkout/Edit.cshtml
@{
    ViewData["Title"] = "Workout edit";
}
@using TrainingDiary.Enums
@model FullWorkout

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @{
        if (User.IsInRole(Role.Coach))
        {
            <partial name="_BaseEventEditPartial" />
            <partial name="_CoachEditPartial" />
        }
        else if (User.IsInRole(Role.Player))
        {
            <partial name="_BaseEventDetailsPartial" />
            <partial name="_PlayerEditPartial" />
        }
    }
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-secondary" />
    </div>
</form>

TrainingDiary/Views/Fullworkout/Index.cshtml
@model IEnumerable<TrainingDiary.Models.FullWorkout>
@using TrainingDiary.Enums;

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EventName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th style="min-width: 150px">
                @if (User.IsInRole(Role.Coach))
                {
                    <a class="btn btn-secondary" asp-controller="FullWorkout" asp-action="Create">Create New</a>
                }
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EventName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    <a asp-controller="Fullworkout" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Fullworkout" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="Fullworkout" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TrainingDiary/Views/Fullworkout/_CoachEditPartial.cshtml
@model TrainingDiary.Models.FullWorkout


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">

            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Plan)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Realization)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.Content)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.Content" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Content" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.Content" class="form-control" />
                    <span asp-validation-for="@Model.Realization.Content" class="text-danger"></span>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.OWB1)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.OWB1" class="form-control" />
                    <span asp-validation-for="@Model.Plan.OWB1" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.OWB1" class="form-control" />
                    <span asp-validation-for="@Model.Realization.OWB1" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.OWB2)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.OWB2" class="form-control" />
                    <span asp-validation-for="@Model.Plan.OWB2" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.OWB2" class="form-control" />
                    <span asp-validation-for="@Model.Realization.OWB2" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.WB3)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.WB3" class="form-control" />
                    <span asp-validation-for="@Model.Plan.WB3" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.WB3" class="form-control" />
                    <span asp-validation-for="@Model.Realization.WB3" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.ZB)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.ZB" class="form-control" />
                    <span asp-validation-for="@Model.Plan.ZB" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.ZB" class="form-control" />
                    <span asp-validation-for="@Model.Realization.ZB" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.KR)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.KR" class="form-control" />
                    <span asp-validation-for="@Model.Plan.KR" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.KR" class="form-control" />
                    <span asp-validation-for="@Model.Realization.KR" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.GL)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.GL" class="form-control" />
                    <span asp-validation-for="@Model.Plan.GL" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.GL" class="form-control" />
                    <span asp-validation-for="@Model.Realization.GL" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.DL)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.DL" class="form-control" />
                    <span asp-validation-for="@Model.Plan.DL" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.DL" class="form-control" />
                    <span asp-validation-for="@Model.Realization.DL" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.Rhythm)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.Rhythm" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Rhythm" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.Rhythm" class="form-control" />
                    <span asp-validation-for="@Model.Realization.Rhythm" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.RelativeSpeed)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.RelativeSpeed" class="form-control" />
                    <span asp-validation-for="@Model.Plan.RelativeSpeed" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.RelativeSpeed" class="form-control" />
                    <span asp-validation-for="@Model.Realization.RelativeSpeed" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.MaxSpeed)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.MaxSpeed" class="form-control" />
                    <span asp-validation-for="@Model.Plan.MaxSpeed" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.MaxSpeed" class="form-control" />
                    <span asp-validation-for="@Model.Realization.MaxSpeed" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.Skip)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.Skip" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Skip" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.Skip" class="form-control" />
                    <span asp-validation-for="@Model.Realization.Skip" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.MultipleJump)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.MultipleJump" class="form-control" />
                    <span asp-validation-for="@Model.Plan.MultipleJump" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.MultipleJump" class="form-control" />
                    <span asp-validation-for="@Model.Realization.MultipleJump" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.MS)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.MS" class="form-control" />
                    <span asp-validation-for="@Model.Plan.MS" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.MS" class="form-control" />
                    <span asp-validation-for="@Model.Realization.MS" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.BPG)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.BPG" class="form-control" />
                    <span asp-validation-for="@Model.Plan.BPG" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.BPG" class="form-control" />
                    <span asp-validation-for="@Model.Realization.BPG" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.KMStart)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.KMStart" class="form-control" />
                    <span asp-validation-for="@Model.Plan.KMStart" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.KMStart" class="form-control" />
                    <span asp-validation-for="@Model.Realization.KMStart" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.Scamper)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.Scamper" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Scamper" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Realization.Scamper" class="form-control" />
                    <span asp-validation-for="@Model.Realization.Scamper" class="text-danger"></span>
                </div>
            </td>
        </tr>

        <tr>
            <th scope="row">
                @Html.DisplayNameFor(model => model.Plan.Comment)
            </th>
            <td>
                <div class="form-group">
                    <input asp-for="@Model.Plan.Comment" class="form-control" />
                    <span asp-validation-for="@Model.Plan.Comment" class="text-danger"></span>
                </div>
            </td>
            <td>
                @Html.DisplayFor(model => model.Realization.Comment)
            </td>
        </tr>

    </tbody>
</table>