TrainingDiary/Models/Camp.cs
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Collections.Generic;
using System.Drawing;
using TrainingDiary.Enums;

namespace TrainingDiary.Models
{
    public class Camp : BaseEvent
    {
        private readonly ILazyLoader lazyLoader;
        private List<FullWorkout> trainingList = new List<FullWorkout>();

        public string Location { get; set; }
		public List<FullWorkout> TrainingList 
        {
            get => lazyLoader.Load(this, ref trainingList);
            set => trainingList = value;
        }

        public Camp()
        {
            Type = EventType.Camp;
            CalendarColor = ColorTranslator.ToHtml(Color.Green);
        }

        Camp(ILazyLoader lazyLoader) : this()
        {
            this.lazyLoader = lazyLoader;
        }
    }
}

TrainingDiary/Controllers/CampController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrainingDiary.Enums;
using TrainingDiary.Models;
using TrainingDiary.Services;

namespace TrainingDiary.Controllers
{
    [Authorize]
    public class CampController : Controller
    {
        private readonly IDbContextService _dbContextService;
        private readonly IUserService _userService;

        public CampController(IDbContextService dbContextService, IUserService userService)
        {
            _dbContextService = dbContextService;
            _userService = userService;
        }

        private bool IsCampRelatedToCurrentUser(Camp camp)
        {
            string userId = _userService.GetUserId(User);
            if (User.IsInRole(Role.Player))
            {
                if (camp.Player == null || camp.Player.Id != userId)
                {
                    return false;
                }
            }
            else if (User.IsInRole(Role.Coach))
            {
                if (camp.Coach == null || camp.Coach.Id != userId)
                {
                    return false;
                }
            }

            return true;
        }

        // GET: Camp/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Camp camp = await _dbContextService.GetCampByIdAsync((int)id);

            if (camp == null || !IsCampRelatedToCurrentUser(camp))
            {
                return NotFound();
            }

            return View(camp);
        }

        // GET: Camp/Create
        [Authorize(Roles = Role.Coach)]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Camp/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Role.Coach)]
        public async Task<IActionResult> Create(Camp camp)
        {
            if (ModelState.IsValid)
            {
                camp.Player = await _userService.GetUserByEmail(camp.PlayerEmail) as Player;
                camp.Coach = await _userService.GetUser(User) as Coach;
                await _dbContextService.AddObjectToDb(camp);
                await _dbContextService.SetConnectionToFullworkout(camp);

                return RedirectToAction("Index", "Events");
            }
            return View(camp);
        }

        // GET: Camp/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Camp camp = await _dbContextService.GetCampByIdAsync((int)id);
            if (camp == null || !IsCampRelatedToCurrentUser(camp))
            {
                return NotFound();
            }

            return View(camp);
        }

        // POST: Camp/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Location,Id,EventName,StartDate,EndDate,Type")] Camp camp)
        {
            if (id != camp.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _dbContextService.SetConnectionToFullworkout(camp);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dbContextService.CampExists(camp.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Events");
            }
            return View(camp);
        }

        // GET: Camp/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camp = await _dbContextService.GetCampByIdAsync((int)id);
            if (camp == null || !IsCampRelatedToCurrentUser(camp))
            {
                return NotFound();
            }

            return View(camp);
        }

        // POST: Camp/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var camp = await _dbContextService.GetCampByIdAsync(id);
            await _dbContextService.RemoveCampFromDb(camp);

            return RedirectToAction("Index", "Events");
        }
    }
}

TrainingDiary/Views/Camp/Create.cshtml
@model TrainingDiary.Models.Camp

<h4>Camp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <partial name="_BaseEventCreatePartial" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingDiary/Views/Camp/Delete.cshtml
@model TrainingDiary.Models.Camp

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Camp</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
    </form>
</div>

TrainingDiary/Views/Camp/Details.cshtml
@{
    ViewData["Title"] = "Camp details";
}
@model Camp

<partial name="_BaseEventDetailsPartial" />
<h6>@Html.DisplayFor(model => model.Location)</h6>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.TrainingList[0].EventName)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.TrainingList[0].StartDate)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.TrainingList[0].EndDate)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (FullWorkout training in Model.TrainingList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => training.EventName)
                </td>
                <td>
                    @Html.DisplayFor(x => training.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(x => training.EndDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="FullWorkout" asp-route-id="@training.Id">Edit</a> |
                    <a asp-action="Details" asp-controller="FullWorkout" asp-route-id="@training.Id">Details</a> |
                    <a asp-action="Delete" asp-controller="FullWorkout" asp-route-id="@training.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TrainingDiary/Views/Camp/Edit.cshtml
@model TrainingDiary.Models.Camp
@using TrainingDiary.Enums


<h4>Camp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (User.IsInRole(Role.Coach))
            {
                <partial name="_BaseEventEditPartial" />
            }
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrainingDiary/Views/Camp/Index.cshtml
@model IEnumerable<TrainingDiary.Models.Camp>
@using TrainingDiary.Enums;

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th style="min-width: 150px">
                @if (User.IsInRole(Role.Coach))
                {
                    <a class="btn btn-secondary" asp-controller="Camp" asp-action="Create">Create New</a>
                }
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    <a asp-controller="Camp" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Camp" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="Camp" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>